# Generated by Django 5.1.3 on 2025-03-10 11:17

import django.db.models.deletion
import home.models
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vision', models.TextField()),
                ('mission', models.TextField()),
                ('theme_title', models.CharField(max_length=100)),
                ('theme_description', models.TextField()),
                ('theme_document', models.FileField(upload_to=home.models.upload_to)),
                ('strategic_plan_title', models.CharField(max_length=100)),
                ('strategic_plan_document', models.FileField(upload_to=home.models.upload_to)),
            ],
            options={
                'verbose_name': 'about us',
                'verbose_name_plural': 'about us',
            },
        ),
        migrations.CreateModel(
            name='Albums',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'album',
                'verbose_name_plural': 'albums',
            },
        ),
        migrations.CreateModel(
            name='AnnualReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('cover_image', models.ImageField(upload_to=home.models.upload_to)),
                ('annual_report_document', models.FileField(upload_to=home.models.upload_to)),
            ],
            options={
                'verbose_name': 'annual report',
                'verbose_name_plural': 'annual reports',
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to=home.models.upload_to)),
            ],
            options={
                'verbose_name': 'banner',
                'verbose_name_plural': 'banners',
            },
        ),
        migrations.CreateModel(
            name='CoreValueItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'core value item',
                'verbose_name_plural': 'core value items',
            },
        ),
        migrations.CreateModel(
            name='DepartmentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_image', models.ImageField(upload_to='course_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('document_type', models.CharField(choices=[('charter', 'Charter'), ('constitution', 'Constitution'), ('strategicplan', 'StrategicPlan'), ('regulations', 'Regulations'), ('tenders', 'Tenders')], max_length=100)),
                ('edition', models.CharField(blank=True, max_length=100, null=True)),
                ('tender_date', models.DateField()),
                ('owner', models.CharField(default='AG', max_length=250)),
                ('document_file', models.FileField(upload_to=home.models.upload_to)),
            ],
            options={
                'verbose_name': 'document',
                'verbose_name_plural': 'documents',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
                ('location', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('event_image', models.ImageField(blank=True, null=True, upload_to=home.models.upload_to)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(blank=True, max_length=100, null=True)),
                ('message', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('reviewed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'feedback',
                'verbose_name_plural': 'feedbacks',
            },
        ),
        migrations.CreateModel(
            name='FormsAndDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=250)),
                ('author', models.CharField(max_length=150)),
                ('publication_date', models.DateField()),
                ('form_and_document_file', models.FileField(upload_to=home.models.upload_to)),
            ],
            options={
                'verbose_name': 'form and document',
                'verbose_name_plural': 'forms and documents',
            },
        ),
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ag_email', models.EmailField(max_length=254)),
                ('ag_phone', models.CharField(max_length=20)),
                ('ag_call_center', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'header',
                'verbose_name_plural': 'headers',
            },
        ),
        migrations.CreateModel(
            name='MonitoringAndEvaluations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('monitoring_and_evaluation_document', models.FileField(upload_to=home.models.upload_to)),
            ],
            options={
                'verbose_name': 'monitoring and evaluation',
                'verbose_name_plural': 'monitoring and evaluations',
            },
        ),
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date_published', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('news_image', models.ImageField(blank=True, null=True, upload_to=home.models.upload_to)),
                ('is_featured', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='NewsLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('cover_image', models.ImageField(upload_to=home.models.upload_to)),
                ('newsletter_document', models.FileField(upload_to=home.models.upload_to)),
            ],
            options={
                'verbose_name': 'newsLetter',
                'verbose_name_plural': 'newsLetters',
            },
        ),
        migrations.CreateModel(
            name='Overview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overview', models.TextField()),
            ],
            options={
                'verbose_name': 'overview',
                'verbose_name_plural': 'overview',
            },
        ),
        migrations.CreateModel(
            name='Policies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('edition', models.CharField(max_length=100)),
                ('policies_document', models.FileField(upload_to=home.models.upload_to)),
            ],
            options={
                'verbose_name': 'policy',
                'verbose_name_plural': 'policies',
            },
        ),
        migrations.CreateModel(
            name='SecretariateStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hierarchy', models.CharField(choices=[('S1', 'Secretariate 1'), ('S2', 'Secretariate 2'), ('S3', 'Secretariate 3'), ('S4', 'Secretariate 4'), ('S5', 'Secretariate 5'), ('S6', 'Secretariate 6'), ('S7', 'Secretariate 7'), ('S8', 'Secretariate 8'), ('S9', 'Secretariate 9'), ('S10', 'Secretariate 10'), ('S11', 'Secretariate 11'), ('S12', 'Secretariate 12'), ('S13', 'Secretariate 13'), ('S14', 'Secretariate 14'), ('S15', 'Secretariate 15')], max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('profile_image', models.ImageField(upload_to=home.models.upload_to)),
            ],
            options={
                'verbose_name': 'attorney general structure',
                'verbose_name_plural': 'attorney general structure',
            },
        ),
        migrations.CreateModel(
            name='SpeechesAndPresentations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=350)),
                ('speaker', models.CharField(max_length=150)),
                ('speech_and_presentation_document', models.FileField(upload_to=home.models.upload_to)),
            ],
            options={
                'verbose_name': 'speech and presentation',
                'verbose_name_plural': 'speeches and presentations',
            },
        ),
        migrations.CreateModel(
            name='StandardOperationProcedures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('edition', models.CharField(max_length=100)),
                ('standard_operation_procedure_document', models.FileField(upload_to=home.models.upload_to)),
            ],
            options={
                'verbose_name': 'standard operation procedure',
                'verbose_name_plural': 'standard operation procedures',
            },
        ),
        migrations.CreateModel(
            name='Tenders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tender_date', models.DateField()),
                ('title', models.CharField(max_length=250)),
                ('owner', models.CharField(max_length=150)),
                ('tender_file', models.FileField(upload_to=home.models.upload_to)),
            ],
            options={
                'verbose_name': 'tender',
                'verbose_name_plural': 'tenders',
            },
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_name', models.CharField(max_length=100)),
                ('video_link', models.URLField()),
            ],
            options={
                'verbose_name': 'video',
                'verbose_name_plural': 'videos',
            },
        ),
        migrations.CreateModel(
            name='AlbumPictures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to=home.models.upload_to)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.albums')),
            ],
            options={
                'verbose_name': 'album picture',
                'verbose_name_plural': 'album pictures',
            },
        ),
        migrations.CreateModel(
            name='CoreValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('items', models.ManyToManyField(blank=True, to='home.corevalueitem')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(max_length=20)),
                ('department_images', models.ManyToManyField(blank=True, to='home.departmentimage')),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date_published', models.DateField()),
                ('summary', models.TextField()),
                ('document', models.FileField(upload_to='publications/')),
                ('category', models.CharField(blank=True, choices=[('Legislation', 'Legislation'), ('Legal Opinions', 'Legal Opinions'), ('Publications', 'Publications'), ('Other', 'Other')], default='Other', max_length=255)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.department')),
            ],
        ),
        migrations.CreateModel(
            name='Legislation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('bill_number', models.CharField(max_length=50, unique=True)),
                ('summary', tinymce.models.HTMLField()),
                ('status', models.CharField(choices=[('Department', 'Department Progress'), ('Ministry', 'Ministry Clarification'), ('Drafting', 'Drafting'), ('Dispatched', 'Dispacthed to Ministries'), ('Cabinet', 'Cabinet/CCL'), ('SubmittedToParliament', 'Submitted to Parliament')], max_length=50)),
                ('received_date', models.DateField(blank=True, null=True)),
                ('dispatched_date', models.DateField(blank=True, null=True)),
                ('cabinet_date', models.DateField(blank=True, null=True)),
                ('pres_to_parl_date', models.DateField(blank=True, null=True)),
                ('leg_file', models.FileField(blank=True, null=True, upload_to=home.models.upload_to)),
                ('leg_image', models.ImageField(blank=True, null=True, upload_to=home.models.upload_to)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.department')),
            ],
            options={
                'indexes': [models.Index(fields=['bill_number'], name='home_legisl_bill_nu_4aeb55_idx'), models.Index(fields=['status'], name='home_legisl_status_7d532b_idx')],
            },
        ),
    ]
