# Generated by Django 5.1.3 on 2025-03-11 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_department_contact_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legislation',
            name='summary',
            field=models.TextField(),
        ),
    ]
